### ISSUE TITLE
Theme Editor

### ISSUE THREAD

**Issue by UnclearGhostGT** [statping-ng/statping-ng#103]
Was attempting to edit the "Theme" when i got this error:

failed to compile assets, exit status 65 Internal Error: File to read not found or unreadable: /app/assets/scss/index.scss
: exit status 65

I'm running a similar docker instance:

```
statping:
  container_name: statping
  image: adamboutcher/statping-ng:latest
  restart: always
  ports:
    - 8080:8080
  volumes:
    - statping_data:/app
  links:
    - postgres
  depends_on:
    - postgres
  environment:
    DB_CONN: postgres
    DB_HOST: postgres
    DB_PORT: 5432
    DB_DATABASE: statping
    DB_USER: root
    DB_PASS: password123

postgres:
  container_name: postgres
  image: postgres:10.0-alpine
  ports:
    - 5432:5432
  volumes:
    - pg_data:/var/lib/postgresql/data/pg_data
  environment:
    POSTGRES_PASSWORD: password123
    POSTGRES_DB: statping
    POSTGRES_USER: root
    POSTGRES_PORT: 5432
    PGDATA: /var/lib/postgresql/data/pg_data
```
