### ISSUE TITLE
[BUG] HTTP_PROXY incorrectly used

### ISSUE THREAD

**Issue by vintury** [statping-ng/statping-ng#145]
Hello.
I have problem with working statping via http proxy.
I have error: 
```
statping  | WARN[0014] Service Google Failing: HTTP Error Get "https://google.com": proxyconnect tcp: dial tcp 10.0.0.100:3128: i/o timeout (Client.Timeout exceeded while awaiting headers) | Lookup in: 5217 μs  type=service
statping  | WARN[0024] Service Statping Github Failing: HTTP Error Get "https://github.com/statping-ng/statping-ng": context deadline exceeded (Client.Timeout exceeded while awaiting headers) | Lookup in: 61 ms  type=service
statping  | WARN[0034] Service Google Failing: HTTP Error Get "https://google.com": context deadline exceeded (Client.Timeout exceeded while awaiting headers) | Lookup in: 68 ms  type=service
statping  | WARN[0034] Service JSON API Tester Failing: HTTP Error Post "https://jsonplaceholder.typicode.com/posts": context deadline exceeded (Client.Timeout exceeded while awaiting headers) | Lookup in: 86 ms  type=service
```
My docker-compose.yaml:
```
version: '2.3'
services:
  statup:
    container_name: statping
    image: private-registry/statping:0.90.80
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./logs:/app/logs
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 8080
      HTTP_PROXY: http://proxy.my.domain.dc:3128
      NO_PROXY: 127.0.0.1,localhost,10.0.0.0/16,172.16.0.0/12,192.168.0.0/16,169.254.169.254,.my.domain.dc
      DB_CONN: postgres
      DB_HOST: postgres1.my.domain.dc
      DB_USER: statping
      DB_PASS: db_pass
      DB_DATABASE: statping
    logging:
      driver: "json-file"
      options:
        max-size: 10m
```

My diagnostic say connection via proxy worked correctly:
```
curl -v https://google.com
* About to connect() to proxy proxy.my.domain.dc port 3128 (#0)
*   Trying 10.0.0.100...
* Connected to proxy.my.domain.dc (10.0.0.100) port 3128 (#0)
* Establish HTTP proxy tunnel to google.com:443
> CONNECT google.com:443 HTTP/1.1
> Host: google.com:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.google.com
* 	start date: июн 06 08:29:46 2022 GMT
* 	expire date: авг 29 08:29:45 2022 GMT
* 	common name: *.google.com
* 	issuer: CN=GTS CA 1C3,O=Google Trust Services LLC,C=US
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: google.com
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: https://www.google.com/
< Content-Type: text/html; charset=UTF-8
< Date: Tue, 28 Jun 2022 07:15:24 GMT
< Expires: Thu, 28 Jul 2022 07:15:24 GMT
< Cache-Control: public, max-age=2592000
< Server: gws
< Content-Length: 220
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
< 
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
* Connection #0 to host proxy.my.domain.dc left intact
```
