### ISSUE TITLE
Telegram test gets "could not decode incoming JSON"

### ISSUE THREAD

**Issue by a0s** [statping-ng/statping-ng#208]
It should send test message to chat with bot but it doesn't.
When i press "Test success" i get in logs:
```
ERRO[1172] sending error response for /api/notifier/telegram/test: could not decode incoming JSON  code=422 method=POST type=handlers url=/api/notifier/telegram/test
INFO[1172] /api/notifier/telegram/test (POST) | IP: localhost:8080  load_micro_seconds=2082 method=POST type=handlers url=/api/notifier/telegram/test
```

Telegram settings:
```
Telegram API Token: xxx (bot token from @BotFather)
Channel: "-46399435" (my chat id from @get_id_bot)
Success Data: HASS is currently online!
Failure Data: HASS is currently offline!
```

Docker compose file:
```
  statping:
    image: quay.io/statping-ng/statping-ng:v0.90.80
    container_name: statping
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Statping Server
      - PORT=8080
      - HOST=localhost
      - VERBOSE=4
      - DISABLE_LOGS=false
      - REMOVE_AFTER=120h
      - ALLOW_REPORTS=false
      # Database
      - DB_CONN=postgres
      - DB_DATABASE=${STATPING_POSTGRES_DB}
      - DB_HOST=postgres-statping
      - DB_PORT=5432
      - DB_USER=${STATPING_POSTGRES_USER}
      - DB_PASS=${STATPING_POSTGRES_PASSWORD}
      # Connection
      - LANGUAGE=en
      # Automatic Fills
      - NAME=Hass
      - DOMAIN=http://hass.local:8080
      - ADMIN_USER=${STATPING_ADMIN_USER}
      - ADMIN_PASSWORD=${STATPING_ADMIN_PASSWORD}
      - SAMPLE_DATA=false
    volumes:
      - statping-app:/app
    # user: "${PUID}:${PGID}"
    depends_on:
      - postgres-statping
      - ssh-proxy
```

As a temporary solution i am using [webhook send message to telegram](https://gist.github.com/dideler/85de4d64f66c1966788c1b2304b9caf1)
